### ISSUE TITLE
Sysdig crash and exit in when running inside docker and dumping traces to files

### ISSUE THREAD

**Issue by lingfennan** [draios/sysdig#1221]
I have been running the sysdig:0.23.1 docker image for more than one day on multiple machines to monitor docker container executions, sysdig failed on two of my machines and printed the same error message:
```
cannot add procs tid = 30904, parenttid = 30887, dirname = /host/proc/30887/task
cannot add procs tid = 22259, parenttid = 22258, dirname = /host/proc/22258/task
```

The sysdig command that I am running is:
```
docker run --rm -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v $OUTDIR:$OUTDIR sysdig/sysdig:0.23.1 sysdig -z -C 2048 -w $OUTPATH container.id != host and container.image = $IMAGE_NAME
```

On one machine, sysdig fails when finishing dumping `$OUTPATH22` (size 2G) and starting dumping `$OUTPATH23` (size 0).
One the other machine, sysdig fails when finishing dumping `$OUTPATH35` (size 2G) and starting dumping `$OUTPATH36` (size 0).

Is this problem already solved in dev/master branch? If not, any idea what's the root cause? Thanks!

**Comment by thesrinivas** [comment]
We're seeing this issue. Can someone please comment if there is a fix for this issue?

**Comment by gitdhar** [comment]
We're seeing this issue too. No containers involved. Can anyone please respond if there is a fix?

**Comment by lingfennan** [comment]
The sysdig folks are active on slack channel. I reached out to them and they mentioned that there is no solution. But they suggested workaround: always restart and if you are logging to file, log to filenames with timestamps to avoid override. Hope this helps! I listed my `docker-compose.yml` for reference.

```
version: '3'
services:
    sysdig:
        image: sysdig/sysdig:0.26.1
        container_name: sysdig
        privileged: true
        restart: always
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - /dev:/host/dev
            - /proc:/host/proc:ro
            - /boot:/host/boot:ro
            - /lib/modules:/host/lib/modules:ro
            - /usr:/host/usr:ro
            - ${TRACEDIR}:${TRACEDIR}
        command: bash -c "sysdig -z -C 2048 -qw ${TRACEDIR}.sysdig-$$(date +'%Y%m%d-%H%M%S').scap.gz container.id != host"
```
