### ISSUE TITLE
When Running as a kubernetes pod, Sysdig not Running or Not giving expected results

### ISSUE THREAD

**Issue by saiyam1814** [draios/sysdig#1594]
I am trying to use Sysdig for a pecific purpose of spying users using the command sysdig -c spy_users.
Whn running as a docker container on a VM and them logging to the VM running commands, the docker logs will show the output instantly. Now I tried to run it as a kubernetes pod (Faced 2issues) on a VM and I use below Yaml file 
```
apiVersion: v1
kind: Pod
metadata:
  name: sysdig
spec:
  containers:
  - args:
    - -c
    - spy_users
    command:
    - sysdig
    image: sysdig/sysdig
    imagePullPolicy: IfNotPresent
    name: sysdig
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    volumeMounts:
    - mountPath: /host/var/run/docker.sock
      name: docker
      readOnly: true
    - mountPath: /host/dev
      name: dev
      readOnly: true
    - mountPath: /host/proc
      name: proc
      readOnly: true
    - mountPath: /host/boot
      name: boot
      readOnly: true
    - mountPath: /host/lib/modules
      name: lib
      readOnly: true
    - mountPath: /host/usr
      name: usr
      readOnly: true
    - mountPath: /etc/groups
      name: grp
      readOnly: true
    - mountPath: /etc/passwd
      name: pswd
      readOnly: true
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker
  - hostPath:
      path: /dev
      type: ""
    name: dev
  - hostPath:
      path: /proc
      type: ""
    name: proc
  - hostPath:
      path: /boot
      type: ""
    name: boot
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib
  - hostPath:
      path: /etc/group
      type: ""
    name: grp
  - hostPath:
      path: /usr
      type: ""
    name: usr
  - hostPath:
      path: /etc/passwd
      type: ""
    name: pswd
```

**ISSUE 1: Now above will not run and go in crashloopbackoff and give error as follows :**
```
Unable to load the driver
error opening device /host/dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

**ISSUE 2: I don't know how but in one of my clusters with the same yaml file  it ran with a different issue which was :**  
on the Node it runs when I log in and try to run some commands, do a kubectl logs <pod> I do not see the results, but sometimes after a huge lag I see all the commands that I ran sometime back. But in an ephermal environment where the nodes are coming and going, I need the kubectl logs to be flowing instantly as an when any activity is performed on the CM where the sysdig pod is running so that I can do the auditing if anything wrong happens. Not sure If I have configured something wrong in this case.
